allowHosts:
  - "stethoscope://main"
hostLabels:
  - pattern: "^https://stethoscope\\.((test|prod)\\.)?netflix\\.net$"
    name: Stethoscope
  - pattern: "^https://meechum\\.((test|prod)\\.)?netflix\\.(com|net)$"
    name: Meechum
policyServer:
